name: Precommit - Validate Release
on: [pull_request]
jobs:
  build:
    name: unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: clean disk
        run: |
          sudo swapoff -a
          sudo rm -rf /swapfile /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo apt clean
          docker rmi $(docker images -q) -f
          df -h

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Checkout
        uses: actions/checkout@v2

      - name: Auto generate crd model
        env:
          DOCKER_USERNAME: ${{ secrets.IMAGE_GITHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.IMAGE_GITHUB_TOKEN }}
        run: ./scripts/build.sh v2.0.0.0

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: failure()